### ISSUE TITLE
proxy returns incomplete response

### ISSUE THREAD

**Issue by manish2aug** [eclipse/microprofile-rest-client#208] opened 2019-07-29 09:02 UTC
proxy of client returns incomplete stage for a test 

example code: https://gist.github.com/manish2aug/b4133b9fbedc2175e15b303a0682b552

**Comment by andymc12** [comment] 2019-07-29 15:00
Hi @manish2aug - thanks for reporting this issue.  I believe that the issue is specific to the CXF implementation, so I created CXF JIRA [8080](https://issues.apache.org/jira/browse/CXF-8080) to address it.  

I used your example to verify that this scenario does work in OpenLiberty, but hangs as you found in CXF.  I made a change to OpenLiberty's MPRestClientCallback class that I intended to contribute back to the CXF codebase, but forgot.  Under CXF PR [570](https://github.com/apache/cxf/pull/570), I am contributing it back.  That PR contains a unit test very similar to your example that failed prior to my changes but now passes.  Please feel free to review my changes to ensure that it works for you. 

Since there is no issue with the MP Rest Client spec in general, I will close this issue.  If you have any other questions or concerns, please post them to the CXF JIRA or PR.

Thanks again, Andy

**Closed by andymc12** 2019-07-29 15:00 UTC

**Comment by manish2aug** [comment] 2019-07-30 08:37
Thanks Andy!
